##===- lib/Target/Mandarin/TargetDesc/Makefile ----------------------------===##
#
#                     Vyacheslav Egorov
#
# This file is distributed under the MIT License
#
##===----------------------------------------------------------------------===##

LEVEL = ../../../..
LIBRARYNAME = LLVMMandarinDesc

# Hack: we need to include 'main' target directory to grab private headers
CPP.Flags += -I$(PROJ_OBJ_DIR)/.. -I$(PROJ_SRC_DIR)/..

include $(LEVEL)/Makefile.common
