//===-- MandarinSubtarget.h - Define Subtarget for the Mandarin -------*- C++ -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the Mandarin specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//

#ifndef MANDARIN_SUBTARGET_H
#define MANDARIN_SUBTARGET_H

#include "llvm/Target/TargetSubtargetInfo.h"
#include <string>

#define GET_SUBTARGETINFO_HEADER
#include "MandarinGenSubtargetInfo.inc"

namespace llvm {
class StringRef;

class MandarinSubtarget : public MandarinGenSubtargetInfo {
  virtual void anchor();

public:
  MandarinSubtarget(const std::string &TT, const std::string &CPU,
                 const std::string &FS);

  /// ParseSubtargetFeatures - Parses features string setting specified
  /// subtarget options.  Definition of function is auto generated by tblgen.
  void ParseSubtargetFeatures(StringRef CPU, StringRef FS);

  bool is64Bit() const { return false; }
  std::string getDataLayout() const {
    return "e-p:32:32-i:32:32-f:32:32";
  }
};

} // end namespace llvm

#endif
