##===- lib/Target/Mandarin/TargetInfo/Makefile ----------------------------===##
#
#                     Vyacheslav Egorov
#
# This file is distributed under the MIT License
#
##===----------------------------------------------------------------------===##
LEVEL = ../../../..
LIBRARYNAME = LLVMMandarinInfo

# Hack: we need to include 'main' target directory to grab private headers
CPPFLAGS = -I$(PROJ_OBJ_DIR)/.. -I$(PROJ_SRC_DIR)/..

include $(LEVEL)/Makefile.common
